# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A Gibbs sampler to generate a bivariate normal chain
#' @description A Gibbs sampler to generate a bivariate normal chain
#' @param N the number of samples
#' @param thin the number of between-sample random numbers
#' @param mu1 the mean of the first dimension
#' @param mu2 the mean of the second dimension
#' @param sigma1 the standard deviation of the first dimension
#' @param sigma2 the standard deviation of the second dimension
#' @param rho the correlation of two dimensions
#' @return a random sample of size \code{n}
#' @examples
#' \dontrun{
#' rnC <- gibbsC(2000,1,0,0,1,1,0.9)
#' par(mfrow=c(1,3));
#' plot(rnC[,1],type='l')
#' plot(rnC[,2],type='l')
#' plot(rnC)
#' }
#' @export
gibbsC <- function(N, thin, mu1, mu2, sigma1, sigma2, rho) {
    .Call('_StatComp22012_gibbsC', PACKAGE = 'StatComp22012', N, thin, mu1, mu2, sigma1, sigma2, rho)
}

